### ISSUE TITLE
Provide installation instructions

### ISSUE THREAD

**Issue by matthiasbeyer** [coddingtonbear/inthe.am#181]
Hi.

I'd like to package this for NixOS, but I need install instructions for this! Also dependencies should be listed!

Would highly appreciate!

**Comment by coddingtonbear** [comment]
Hey there @matthiasbeyer; there aren't any instructions and adding those instructions isn't a priority for me.  Feel free to write up some instructions, though, and submit a pull request if you'd like them to be available.

To be clear: Inthe.AM isn't on Github because I had any anticipation that people would want to start up their own Inthe.AM-clones -- it's on Github so users can find bugs, prorotype/design new features, and otherwise maybe use it for ideas on how to structure their own emberjs+django projects.

I'm afraid that the only advice I can give you were you to want to continue on this challenge would be to have a look at the [Vagrantfile](https://github.com/coddingtonbear/inthe.am/blob/development/Vagrantfile) used for setting up a development environment.  There's certainly sufficient information there for spinning-up a development instance, but I'd suggest extreme caution against following the instructions too closely when setting up a public-facing clone.

Cheers, and good luck!

**Comment by matthiasbeyer** [comment]
>  Inthe.AM isn't on Github because I had any anticipation that people would want to start up their own Inthe.AM-clones -- it's on Github so users can find bugs, prorotype/design new features, and otherwise maybe use it for ideas on how to structure their own emberjs+django projects

You should state that somewhere. Probably in the README file.
