### ISSUE TITLE
vagrant shell provisioning errors

### ISSUE THREAD

**Issue by ebayer** [coddingtonbear/inthe.am#198]
init_environment.sh has a couple of annoyances and some errors:

I do not know how to resolve these, I will try to install the latest version for ember-cli, but I do not know how it will affect your project.
* npm throws "unmet dependency" warnings about debug when installing ember-cli (upgrading ember-cli could help according to https://github.com/npm/npm/issues/8241)

Example:
```
==> default: npm
==> default:
==> default: WARN
==> default:
==> default: unmet dependency
==> default:  /usr/lib/node_modules/ember-cli/node_modules/express requires debug@'~2.1.1' but will load
```
Full log: https://gist.github.com/1cbfca3c2a8e1677000c.git

* ember throws an error when building
```
==> default: version: 0.1.7
==> default: Could not find watchman, falling back to NodeWatcher for file system events
==> default: Building
==> default: Building...
==> default: Cannot find module 'ember-cli/lib/broccoli/ember-app'
==> default: Error: Cannot find module 'ember-cli/lib/broccoli/ember-app'
==> default:     at Function.Module._resolveFilename (module.js:338:15)
==> default:     at Function.Module._load (module.js:280:25)
==> default:     at Module.require (module.js:364:17)
==> default:     at require (module.js:380:17)
==> default:     at Object.<anonymous> (/var/www/twweb/Brocfile.js:3:16)
==> default:     at Module._compile (module.js:456:26)
==> default:     at Object.Module._extensions..js (module.js:474:10)
==> default:     at Module.load (module.js:356:32)
==> default:     at Function.Module._load (module.js:312:12)
==> default:     at Module.require (module.js:364:17)
==> default:     at require (module.js:380:17)
```

* python managepy run throws error:
```
(twweb)vagrant@precise32:/var/www/twweb$ python manage.py run
 Note: It will take a few seconds for both necessary
      servers to start.  Once you see the message
      message 'Build Successful', both servers are up.

Validating models...

version: 0.1.7
0 errors found
October 08, 2015 - 17:54:29
Django version 1.6.1, using settings 'inthe_am.settings'
Starting development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
Could not find watchman, falling back to NodeWatcher for file system events
Cannot find module '/var/www/twweb/node_modules/broccoli-ember-hbs-template-compiler'
Error: Cannot find module '/var/www/twweb/node_modules/broccoli-ember-hbs-template-compiler'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at requireLocal (/usr/lib/node_modules/ember-cli/lib/utilities/require-local.js:6:10)
    at TemplatePlugin.toTree (/usr/lib/node_modules/ember-cli/lib/preprocessors/template-plugin.js:16:10)
    at /usr/lib/node_modules/ember-cli/lib/preprocessors.js:104:26
    at Array.forEach (native)
    at processPlugins (/usr/lib/node_modules/ember-cli/lib/preprocessors.js:103:11)
    at module.exports.preprocessTemplates (/usr/lib/node_modules/ember-cli/lib/preprocessors.js:86:10)
```

* npm throws "No README data" warnings
Example:
```
==> default: npm
==> default:
==> default: WARN
==> default:
==> default: package.json
==> default:  broccoli-asset-rev@2.2.0 No README data
```

Full log: https://gist.github.com/1cbfca3c2a8e1677000c.git

I have attached a patch for these following two annoyances, I did not want to create a pull request for something so small:
* in inthe_am/settings.py line 65, MIDDLEWARE_CLASSES should be list, not tuple
* turn off wget progress bar

Patch: https://gist.github.com/222a0dc6cbfcaed52f28.git

**Comment by coddingtonbear** [comment]
Thanks for helping out!  Unfortunately, though, the gists you've posted are private, so I can't see what's in them.

Re: `npm` messages -- those are being reported for modules we require (not modules we write), so if those messages bother you, you'll have better luck contacting the people/teams managing those projects directly.  You can look up the project info for NPM packages on NPM's website -- in `broccoli-asset-rev`'s case, that's here: https://www.npmjs.com/package/broccoli-asset-rev.  Good luck!

Also -- your patch; could you push up those changes and file a pull request?  If you've never done one before, there are a bunch of tutorials on the internet including this one: https://yangsu.github.io/pull-request-tutorial/ (note that you'll be following the 'Pull Request from a forked repository' path).

**Comment by ebayer** [comment]
Which version of npm, ember and bower you are using? Can you attach npm list output?

The gists were not private, but I did not embed the URL's right, here is the correct one:

{% gist 1cbfca3c2a8e1677000c &}

I am still getting the following error when running, this prevents the second server (8000) from running:

```
Could not find watchman, falling back to NodeWatcher for file system events
Cannot find module '/var/www/twweb/node_modules/broccoli-ember-hbs-template-compiler'
Error: Cannot find module '/var/www/twweb/node_modules/broccoli-ember-hbs-template-compiler'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at requireLocal (/usr/lib/node_modules/ember-cli/lib/utilities/require-local.js:6:10)
    at TemplatePlugin.toTree (/usr/lib/node_modules/ember-cli/lib/preprocessors/template-plugin.js:16:10)
    at /usr/lib/node_modules/ember-cli/lib/preprocessors.js:104:26
    at Array.forEach (native)
    at processPlugins (/usr/lib/node_modules/ember-cli/lib/preprocessors.js:103:11)
    at module.exports.preprocessTemplates (/usr/lib/node_modules/ember-cli/lib/preprocessors.js:86:10)
```

Upgrading to latest version of ember and bower seems to fix the issue. If that is ok with you, I can send a seperate pull request for that too.

I will send a pull request for the previous patch.

**Comment by coddingtonbear** [comment]
Although I can't positively identify the ember/bower versions I'm running in my dev environment -- I'm not somewhere where I can access the VM I use for development on Inthe.AM -- but I can say that the requirements file requests `ember@1.8.1`, and the build script installs `bower@1.3.12`.  It doesn't look like I explicitly install `npm` anywhere, and I can't say for sure what version might be running on the Travis-CI continuous integration environment, so that could potentially be a problem that I hadn't noticed before.  It has definitely has happened before that when libraries we depend upon change, that our requirements drift to the point that the VM cannot be brought up -- thanks for noticing that this was a problem and helping out!

We set our ember/bower versions in a few places (although theoretically two should be sufficient -- there are some idiosyncrasies about our continuous integration environment that I never invested the time to figure out) --
* For NPM package requirements: https://github.com/coddingtonbear/inthe.am/blob/development/package.json#L22
* For bower requirements: https://github.com/coddingtonbear/inthe.am/blob/development/bower.json#L6
* Because this happened before, and I thought this fixed it, in the environment build script: https://github.com/coddingtonbear/inthe.am/blob/development/scripts/vagrant/init_environment.sh#L116

I should caution you, though -- you *probably* won't have much luck with the 2.x versions of ember.  There were significant changes and I haven't had much time to spend upgrading things.
