### ISSUE TITLE
Additional OAuth Options

### ISSUE THREAD

**Issue by phillc73** [coddingtonbear/inthe.am#251]
I was wondering if it might be possible to add in additional OAuth providers for inthe.am login. Specifically, I'd be interested in GitLab and maybe GitHub.

**Comment by coddingtonbear** [comment]
Sorry to be the bearer of bad news; this conversation has came up before, and I'm afraid I'm a little more opposed to it than you might guess.  Before I explain; let me be clear: you can totally feel free to turn on as many authentication backends as you'd like if you were to set up your own instance (inthe.am just uses `python-social-auth` for authentication backends; refer to their docs if you're curious about how that works).   That being said, I'm afraid that although `python-social-auth` makes turning those backends on very easy, it still leaves it up to us to manage the user experience of having multiple sign-in options, and to help users out as sign-in options disappear or stop working.  Additionally, if I were to open the gate to allow multiple sign-in backends, we have to be prepared to make a UI that looks nice with perhaps a dozen sign-in options; because at that point, I wouldn't be able to have a compelling case as to why I the GitLab backend is enabled but not the Untappd backend.

Given that I really, really don't have a whole lot of time to devote to this project these days, I'd really much rather keep things as simple as I possibly can, so I'm afraid you're fighting an uphill battle, @phillc73!

**Comment by phillc73** [comment]
Thanks for the detailed reply. I'm not a Python developer, so honestly not likely to install this on my own server. Appreciate your reasoning and no problem.
