### ISSUE TITLE
500 server error when attempting to log in with Google for the first time

### ISSUE THREAD

**Issue by su-narthur** [coddingtonbear/inthe.am#254]
Clicking the "Log in with Google to get started" button takes me to `https://inthe.am/login/google-oauth2/` which displays the message "Server Error (500)". I've tried this using Chrome, a Chrome incognito tab, and Safari. Same results for each.

**Comment by coddingtonbear** [comment]
Thanks for the heads-up @su-narthur!  You should be good-to-go now.  As an FYI, feel free to ping me in the [gitter.im channel](https://gitter.im/coddingtonbear/inthe.am) when this sort of thing occurs.

As it turns out, this specific error was caused by memcached crashing and (apparently) some of my error reporting depending upon that being there.  I've restarted memcached and now things are back on the rails.  I'll look into what the underlying problem was when I have free time someday.

Cheers!
