### ISSUE TITLE
badly formed hexadecimal UUID string

### ISSUE THREAD

**Issue by riklopfer** [coddingtonbear/inthe.am#256]
I encountered a ton of these on log in. I'm running task 2.5.1 on Linux Mint. 

```
An error was encountered while parsing task 042c024c-9a23-4efa-9c82-132025bf1c64; it was omitted from results as a result: badly formed hexadecimal UUID string.
```

**Comment by coddingtonbear** [comment]
Usually that sort of thing happens if your tasks have invalid dependencies; if you run `task export 042c024c-9a23-4efa-9c82-132025bf1c64`, I'm just about 100% sure that you'll see that the `depends` field is malformed.  If you fix it up (and the same problem on any other affected tasks), you should be OK, though!

Good luck!

**Comment by riklopfer** [comment]
Thanks. I think you're right. I'm having trouble importing my old `completed.data` and `pending.data`. Taskwarrior gives, `Error: missing ']' at position 1`

**Comment by coddingtonbear** [comment]
It *sounds* like maybe the data in your old `completed.data` or `pending.data` probably includes the invalid `depends` data, too.  If I were you, I'd hop into #taskwarrior on freenode to see if those folks can help you out -- just mention that you have corrupted `depends` data and they'll know about the problem you're experiencing.
