### ISSUE TITLE
iCal not updating with modified due time

### ISSUE THREAD

**Issue by thornycrackers** [coddingtonbear/inthe.am#261]
Hi!

First I wanted to say thanks for all the work because this is definitely a helpful app to use. One thing I noticed is that when I create a task with a due date I get the event on my google calendar from the iCal link. I tried updating the due date but it did not reflect on the calendar. Is this a known issue? I couldn't find anything on it.

**Comment by coddingtonbear** [comment]
Hmm; it's pretty likely that that's just caching on Google's side, really.  We generate those on-the-fly every time your calendar is requested by them.  You can, though, if you're very curious, look at the iCal file directly by downloading it using the URL on your configuration page, finding that entry, and comparing the due date you read there with what you're expecting.

Could you do that and let me know if it matches; it *should*, and I can't imagine why it wouldn't, but am very curious to hear what you find.

**Comment by bgregos** [comment]
Hey there, I've experienced the same problem. After some googling on the topic, it does appear to have to do with Google caching iCal feeds in Google Calendar, and the problem has been around for quite awhile. The general consensus is that it does update, but it's quite slow (on the order of every other day or so, apparently, but I haven't tested that myself). You can force a manual update by following the instructions I found [here](http://support.teamwork.com/projects/hints-and-tips-133/force-a-refresh-of-your-google-calendar-ical-feed), but that isn't a quick or workable solution. 
A few days ago, I ended up writing a quick-and-dirty python script (my first python script too!) that queries inthe.am at set intervals and transcribes the events into Google Calendar using its API, bypassing the slow iCal syncing. I could tidy it up and post it if anyone might find it helpful.
Ideally Google could fix the problem, but it's been around [a long time](https://productforums.google.com/forum/#!topic/calendar/ixQnzHmWDSk), so moving in events via the Calendar API like my script may be a better option instead of relying on iCal.

**Comment by thornycrackers** [comment]
Yes it appears that everything has synced over to the new date it just took a little bit. Thanks for all the insight and the link to forcing the manual update. :)

**Comment by coddingtonbear** [comment]
I'm glad you guys found the root of the problem!  I'm a little curious to hear about the script you wrote for synchronizing taskwarrior tasks directly with gcal via their API, and would love to see something like that opensourced, @bgregos -- let me know if you have anything you can point me toward!

Cheers!

**Comment by bgregos** [comment]
@coddingtonbear I fixed up the script and published it here: https://github.com/bgregos/inthe.AM_CalendarSync (It's under the Apache License 2.0)

This is my first python program, so I'm definitely open to any feedback. Basically, this works by querying the inthe.am API for a list of tasks, doing some timezone conversions and deduplication, and mantaining a Google Calendar via API.

Hopefully you all find it helpful!
