### ISSUE TITLE
Sync failing with 500 error

### ISSUE THREAD

**Issue by mani-ramaswamy** [coddingtonbear/inthe.am#262]
Getting the 500 error when using task sync:
Sync failed.  The Taskserver returned error: 500 Unrecognized taskwarrior file format.

When logging in to inthe.am, it gives a lot of error notifications that look like

"An error was encountered while parsing task 11f0fbcd-a111-22b3-b2bc-1a38af058fbe; it was omitted from results as a result: badly formed hexadecimal UUID string."

**Comment by coddingtonbear** [comment]
Ahh; those errors are unrelated with one another --

* `500 Unrecognized taskwarrior file format`: Occurs when your task list on the taskserver is corrupted.  It shouldn't ever happen, but if it does, you should do what you did -- clicking the "clear task data" button in the Danger Zone section on the configuration page.  I'm a little curious about how your task list might've become corrupted, though, honestly.
* `500 Client sync key not found`: Occurs when a local copy of your task list disagrees with the taskserver about the last time a synchronization took place.   When a synchronization takes place, your local taskwarrior client checks its `backlog.data` file to find the ID of the last change, and when synchronizing with the taskserver, tells the taskserver that ID number.  If the taskserver *isn't* aware of that ID number, you'll see the above error message (and it won't be if you've clicked the 'Clear Task Data' button).  If it *is* aware of that ID number, it'll let your client know what changes have taken place since the point in time identified by that ID number.

To resolve the last problem, what you want to do now is run `task sync init` using your local taskwarrior client.  This will tell your local taskwarrior client to upload _all_ of its changes, and not attempt to negotiate with the taskserver regarding which changes were more recent than the most recent upgrade.

**Comment by mani-ramaswamy** [comment]
On my WIndows client, it iis working fine now. I did do the task sync init, and everything is fine.

However, from my Mac, I am still getting the client sync key error (earlier it was the unrecognized format error). I am reticent to do a task sync init from the mac, since it is now 12-18 hours behind....  should I still do a task sync init?

**Comment by coddingtonbear** [comment]
I think given the above description of how this works, it might make sense to you why that is the case -- your mac is still trying to synchronize as if you hadn't clicked "Clear Task Data" earlier today.  Since you've _already_ ran `task sync init` from one of your local clients, you do *not* want to run it on another.  What's probably a better option is instead deleting all of your task information from your mac client and re-synchronizing with the task server as if it were a completely new copy of your task list.

**Comment by mani-ramaswamy** [comment]
Did that. But not sure, why it suddenly started failing (and that was also only on the mac). Anyways, removing ~/.task and then syncing worked. THanks for your help.

**Comment by coddingtonbear** [comment]
Awesome; I'm glad that you're sorted out again.  Also; if you ever bump into a problem like this in the future, feel free to say something in [the gitter channel](https://gitter.im/coddingtonbear/inthe.am); I'm usually on there and can talk you through troubleshooting steps in realtime.
