### ISSUE TITLE
API request to add a task

### ISSUE THREAD

**Issue by ravl1084** [coddingtonbear/inthe.am#272]
Hi,
I'm experimenting with the REST API, using this request as a test:
```
curl -v -X POST -H "Authorization: Token MYTOKEN" https://inthe.am/api/v2/tasks/ -d '{"description":"test task","project": "tickler", "tags":["home","actions"]}'
```

The server responds `{"description":["This field is required."]}` and no task is created.

**Comment by coddingtonbear** [comment]
@ravl1084 & I talked this over in the gitter channel, but the root of this problem is that the content-type isn't declared, and a different content-type (almost certainly `multipart/form-data`) is being assumed by the API.  The solution here is to specify the content-type explicitly by adding a `Content-Type: application/json` header (in the above case, adding `-H "Content-Type: application/json"`).
