### ISSUE TITLE
Enable travis builds for pull-requests

### ISSUE THREAD

**Issue by Tzrlk** [coddingtonbear/inthe.am#281]
The deployment and notification steps in the travis build configuration should be able to be restricted to the core repo/branch so build checking can occur during pull-request submission. Can this be enabled please?

**Comment by coddingtonbear** [comment]
Although I understand why you might find it useful, I'm afraid it's impossible!  The existing tests rely upon a handful of secret keys (via [encrypted environment variables](https://docs.travis-ci.com/user/environment-variables/#Defining-encrypted-variables-in-.travis.yml)) for accessing services like Trello, AWS/S3, and BrowserStack.  Those encrypted environment variables can't be used on pull request builds because it would be trivial for somebody post a pull request that might expose the decrypted value of those variables.

Tests can, though, be successfully run locally if you add your own keys.  Sorry that there isn't an easier way!

**Comment by Tzrlk** [comment]
Damn. Ah well, good to have this documented at least. Thanks for the
clarification.
