### ISSUE TITLE
badly formed hexadecimal UUID string

### ISSUE THREAD

**Issue by ilvetz** [coddingtonbear/inthe.am#283]
Blocked tasks depending on others produce the following error in logs (annoying in the UI):

_An error was encountered while parsing task xxx; it was omitted from results as a result: badly formed hexadecimal UUID string._

**Comment by coddingtonbear** [comment]
That _usually_ happens if you have tasks that have incorrectly-encoded dependencies -- have a look at these historical closed issues for a little more information

* https://github.com/coddingtonbear/inthe.am/issues/256
* https://github.com/coddingtonbear/inthe.am/issues/232

This is the underlying bug ticket in Taskwarrior itself: https://bug.tasktools.org/browse/TD-104.
