### ISSUE TITLE
Labels removed on the Trello side are coming back.

### ISSUE THREAD

**Issue by oktayaa** [coddingtonbear/inthe.am#288]
Using the Trello integration, when I delete a Label from a Trello card, a few seconds later the label comes back. I am assuming this is coming from the inthe.am side.

**Comment by coddingtonbear** [comment]
That's something I've noticed happen, too!  Really: certain kinds of changes in Trello seem to be lost in certain situations.

Unfortunately, I am not likely to find the time to look into that anytime in the forseeable future; maybe you could post a pull request fixing whatever the logical glitch is?

**Comment by oktayaa** [comment]
How are you handling the two way sync? Is there a time to wait or something like that?

**Comment by coddingtonbear** [comment]
Ahh; the way it works right now is dependent upon webhook messages from Trello, and then Inthe.AM updating messages in Trello when we find changes:

* For changes coming  *from* trello:
    * In this file, you can find the URL to which trello will post changes you make to your task list: https://github.com/coddingtonbear/inthe.am/blob/590ad1378b0a341fb72164cd435ee97673519dde/inthe_am/taskmanager/urls.py#L60
    * And that'll call https://github.com/coddingtonbear/inthe.am/blob/590ad1378b0a341fb72164cd435ee97673519dde/inthe_am/taskmanager/viewsets/task.py#L451
    * Which will spawn an offline task using the received JSON: https://github.com/coddingtonbear/inthe.am/blob/590ad1378b0a341fb72164cd435ee97673519dde/inthe_am/taskmanager/tasks.py#L441
    * Which will call https://github.com/coddingtonbear/inthe.am/blob/590ad1378b0a341fb72164cd435ee97673519dde/inthe_am/taskmanager/models/trelloobjectaction.py#L26 and itself will call one of the many `reconcile_*` methods to actually update the task in your task list.
* For changes going *to* trello:
    * Your task list on the server is stored in a git repository; during a sync, we'll check to see if any tasks were changed https://github.com/coddingtonbear/inthe.am/blob/590ad1378b0a341fb72164cd435ee97673519dde/inthe_am/taskmanager/models/taskstore.py#L750 , and, if so,
    * Call this offline task that will check your task list, and update Trello to match it: https://github.com/coddingtonbear/inthe.am/blob/5a1178aa0786b3eae655dc3a1faf00e07ca87a87/inthe_am/taskmanager/tasks.py#L460 causing us to synchronize your task list with Trello

I'm not totally sure where this bug is likely to lie, but it could be in one of a few places:

* It's a race condition in which, after receiving a message from Trello indicating that you've removed a tag, we're firing `update_trello` *before* updating your local task list to remove a task, so it just adds the tag back (because your task list still has it).
* It's a race condition in which we're otherwise asynchronously processing older messages after having made changes that invalidate the older messages.  Really, Inthe.AM should record the current timestamp when sending changes to Trello, and ignore any messages from Trello for a given task if that timestamp is in the past.  I haven't added that, though, and although I'd like to, I'm not going to find the time in the foreseeable future.
* It's a problem in how the trello task is merged with your local task (see one of the `reconcile_*` methods mentioned above).
* It's some problem I haven't even thought of before.

This isn't the kind of thing you're likely to be able to figure out immediately out-of-the-gate, but if you really want to fix it, you can totally feel free to hit me up on the [gitter.im](https://gitter.im/coddingtonbear/inthe.am) channel for help/tips, and, if I just happen to not be super busy, maybe extra eyes for troubleshooting.

**Comment by coddingtonbear** [comment]
Fixed this up just the other day as part of updating the method used for mapping between Taskwarrior tasks and Trello labels for the latest version of the Trello API.  The fix involved changing the strategy used for identifying which labels need to be removed and which need to be added (see https://github.com/coddingtonbear/inthe.am/compare/6d0be...31bbc67 if you're feeling curious).
