### ISSUE TITLE
The iCal export includes the date but not the time of the task. Consequently, they show up on my calendar as all day tasks.

### ISSUE THREAD

**Issue by joshdoyle** [coddingtonbear/inthe.am#326]
The iCal export includes the date but not the time of the task. Consequently, they show up on my calendar as all day tasks. See this image that shows my fantastical calendar overlayed by my terminal output. 

Is this by design? Could this be implemented?

<img width="961" alt="image" src="https://user-images.githubusercontent.com/1417704/79706056-7d201980-827d-11ea-9e78-263fcedfffbb.png">

**Comment by coddingtonbear** [comment]
That's intentional, unfortunately.  Due to the RFC5545 standard used for these calendars, every entry has a start date and end date regardless of whether we specify the end date explicitly -- if we don't provide an end date, that end date will be assumed to be one day later: https://stackoverflow.com/questions/15295887/does-an-ical-file-have-to-have-an-enddate.

I'm afraid I can't think of a way of making this better, but do feel free to start a discussion on the gitter channel if you can think of something.  Also, if you were wanting to consider a PR, the particular view handling this is here: https://stackoverflow.com/questions/15295887/does-an-ical-file-have-to-have-an-enddate
