### ISSUE TITLE
Alternative to Google login

### ISSUE THREAD

**Issue by pataquets** [coddingtonbear/inthe.am#346]
The public service forces you to use Google to login.
If you want to avoid Google, is there any alternative?
* Classic username and password.
* Other OAuth provider, such as GitHub.

**Comment by coddingtonbear** [comment]
I'm afraid there's no alternative right now for Inthe.am, but that's mostly because I need to keep the maintenance burden of this down to an absolute minimum, and adding an additional auth provider does introduce a handful of unwanted complexities (see #251)

If you were to set up your own instance, it wouldn't be terribly difficult to configure things to use any auth provider supported by python-social-auth.  No plans for that for Inthe.am, though, I'm afraid!
