### ISSUE TITLE
CORS Header for the API

### ISSUE THREAD

**Issue by takl95** [coddingtonbear/inthe.am#351]
Would it be possible to add the following header to the API Response?

Access-Control-Allow-Origin: *

It would allow CORS request.

Relevance: I'm working on a static web-app frontend that would use the API on the client-side (browser only). This is not possible without the header.

**Comment by harrisonhjones** [comment]
From a security prospective it would likely be better to allow for the header to be customized via some kind of config so users could lock it down properly.

Since only a single origin can be specified ([ref](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin)) it would likely make sense to have this config variable be a list of allowed origins. If the incoming origin matched one on the list the header could be set; if not, don't set the header.

**Comment by coddingtonbear** [comment]
I'm afraid I'm pretty opposed at the moment, given my understanding of the security implications -- the API right now allows _both_ session auth and token auth, and turning off session auth is a non-starter given that the UI is right now reliant upon it.  In the option you present, @harrisonhjones, does the browser even allow the CORS pre-flight to be credentialed?

**Comment by harrisonhjones** [comment]
> @harrisonhjones, does the browser even allow the CORS pre-flight to be credentialed?

Yes, I think so. Ref https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Credentials

> the API right now allows both session auth and token auth

based on https://intheam.readthedocs.io/en/latest/api/authentication.html I think it should be ok, from a security prospective, to add support for API key specific CORS origin responses. It feels a bit hacky bit you could save the allowed origins with the API key (with the default being none) and then, when you do the API key lookup, set the appropriate origin (if it matches the incoming one). I would then, as special case, NOT allow `*`.

**Comment by coddingtonbear** [comment]
I'm afraid it's extremely unlikely I'm going to find the time to convince myself that this is a safe thing to change, and after that I'd still need to find the time to actually do the work to implement that; so I'm afraid that since for the forseeable future this is probably not a thing I'm going to be able to move forward on, I'm going to close this as "Won't fix".

Definitely feel free to try to convince me out of that if you can make a proof-of-concept PR demonstrating this using Inthe.AM's codebase & showing that this doesn't open up a hole allowing third-party sites to access account information via XHR, but all of the work on this would have to be taken on by somebody else.

Until then, I'm going to close this as a "won't fix", but definitely reach out if either of you are willing to take on the work described above!
