### ISSUE TITLE
Google Oauth Flow gives 500

### ISSUE THREAD

**Issue by StephanMeijer** [coddingtonbear/inthe.am#403]
On the Google OAuth flow on inthe.am website I get a 500.
<img width="304" alt="image" src="https://user-images.githubusercontent.com/3169264/193632653-55c6f4ed-6007-4991-9a97-ca29adef62fc.png">

**Comment by narcolepsy** [comment]
This has been fixed by @coddingtonbear

**Comment by newptcai** [comment]
I am getting the same error.

**Comment by coddingtonbear** [comment]
I'm not seeing an error around this; so I'm going to assume this was a brief glitch at some point.

**Comment by hbjydev** [comment]
@coddingtonbear I'm getting this now, just tried to use it

**Comment by xiian** [comment]
Seeing this for at least a day now.

I know this issue is closed and that maintenance on this repo is not top priority, but figured I'd add some more context to the issue in case it helps at all.

# Web
The Google side of things goes fine, but it redirects back to `https://inthe.am/complete/google-oauth2/` with `state`, `code`, `scope`, `authuser` and `prompt` all populated in the query string. But only the `Server Error (500)` page shown. 

Clearing cookies has no effect.

I do notice that a `sessionid` cookie is set when I first load the page (and get the 500).

If I refresh the page, I still get the 500, but a _new_ cookie is set  for `messages` and it contains "Authentication process canceled" and "social-auth google-oauth2" in the midst of some serialization bits. Every refresh after that adds _another_ set of those to the cookie.


# CLI
Running `task sync` locally fails with:
```
Syncing with taskwarrior.inthe.am:53589

Sync failed.  Either your credentials are incorrect, or your account doesn't exist on the Taskserver.
```

Running `task rc.debug=1 rc.debug.tls=2 sync` to get more info shows that we're getting a `430` response back:
```
c: 2 HSK[0x14882da00]: sent server name: 'taskwarrior.inthe.am'
c: 2 EXT[0x14882da00]: client generated SECP256R1 shared key
c: INFO Handshake was completed: (TLS1.3)-(ECDHE-SECP256R1)-(RSA-PSS-RSAE-SHA256)-(AES-256-GCM)
c: INFO Sending 'XXXXclient: task 2.6.2
key: {redacted}
org: inthe_am
protocol: v1
type: sync
user: {redacted}

{redacted}

' (928 bytes)
c: INFO expecting 58 bytes.
c: INFO Receiving 'XXXXclient: taskd 1.1.0
code: 430
status: Access denied


' (58 bytes)
```
